prgrms-web-devcourse-final-project/WEB2_3_CUBE_FE

- index.html
- package.json
- pnpm-lock.yaml
- src/App.tsx
- src/components/EditList.tsx
- src/main.tsx
- src/pages/main/MainPage.tsx
- src/styles/index.css
- src/styles/tailwind.css
- vite.config.ts
`feature/` -> `dev`
tailwindcss 세팅 오류 수정
> 6 - choresettings

- src/components/LayeredButton.tsx
- src/pages/main/MainPage.tsx
`style/button-component` -> `dev`
공통 사용 가능한  버튼 컴포넌트 개발
- prop으로 theme='red'와 같이 전달하면 테마 적용 (red / gray / blue / purple)
- children으로 버튼 내용 전달 받음
- className으로 크기 등 커스텀 가능
https://github.com/prgrms-web-devcourse-final-project/WEB2_3_CUBE_FE/issues/10
> [style/button-component] :lipstick:Style: 버튼 컴포넌트 퍼블리싱

- src/components/AlertModal.tsx
- src/components/ConfirmModal.tsx
- src/pages/LoginPage.tsx
- src/pages/TestPage.tsx
- src/pages/main/MainPage.tsx
- src/routes/Router.tsx
`feature/alertconfirmmodal` -> `dev`
- alert, confirm 공통 모달 컴포넌트 퍼블리싱했습니다.
코드
- onConfirm:  확인을 눌렀을때 실행할 함수를 전달
- onClose : 모달창을 끄기위한 함수 전달
- title: 메인 제목
- subTitle: 서브 제목
> 💄 Style: alert, confirm 모달 컴포넌트 퍼블리싱

- index.html
- src/styles/index.css
`style/font` -> `dev`
기본 폰트로 pretendard 설정
- postCSS에서 계속 충돌이 나서 index.html에 직접 CDN하는 방식으로 해결했습니다
https://github.com/prgrms-web-devcourse-final-project/WEB2_3_CUBE_FE/issues/24
> [style/font] :lipstck:Style: pretendard 폰트 CDN

- src/components/ModalBackground.tsx
- src/components/datalist/DataList.tsx
- src/components/datalist/EditStatusItem.tsx
- src/components/datalist/NoEditStatusItem.tsx
- src/mocks/searchData.ts
- src/pages/bookcase/components/ToolBoxButton.tsx
`style/bookcase-sidebar` -> `dev`
도구 모음 버튼 - 목록 보러가기  버튼에 도서 리스트 사이드 바 연결
-> truncate 적용
-> 도서 리스트인 경우 출판사 정보 추가
https://github.com/prgrms-web-devcourse-final-project/WEB2_3_CUBE_FE/issues/36
> [style/bookcase-sidebar] 💄Style: 목록 보러가기 클릭시 사이드 바 연결

- src/pages/book-editor/BookEditorPage.tsx
- src/pages/book-editor/components/FreeformEditor.tsx
- src/pages/book-viewer/BookViewerPage.tsx
- src/pages/book-viewer/components/BookReviewDisplay.tsx
- src/pages/book/BookPage.tsx
- src/styles/index.css
- src/types/review.ts
`style/bookReview-viewer` -> `dev`
서평 뷰어 페이지를 구현했습니다. 서평 데이터를 표시하고 수정/삭제 기능을 추가했습니다.
https://github.com/prgrms-web-devcourse-final-project/WEB2_3_CUBE_FE/issues/48
> [style/bookReview-viewer] 💄Style: 서평 뷰어 페이지 퍼블리싱

- src/components/SkeletonItem.tsx
- src/components/datalist/DataList.tsx
- src/components/datalist/EditStatusItem.tsx
- src/components/datalist/NoEditStatusItem.tsx
- src/components/search-modal/SearchInput.tsx
- src/mocks/searchData.ts
- src/pages/cd/components/CdPlayer.tsx
- src/pages/cd/components/CommentList.tsx
- src/pages/cdrack/CdRackPage.tsx
- src/styles/tailwind.css
- src/types/dataList.d.ts
`fix/datalist` -> `dev`
datalist(사이드바 컴포넌트) 스타일링 수정했습니다.
- #56
> 🐛 fix: datalist 공통 컴포넌트 스타일링 수정

- src/apis/book.ts
- src/components/header/Header.tsx
- src/components/header/menus/HiddenMenu.tsx
- src/components/header/menus/HousemateModal.tsx
- src/components/header/menus/NotificationModal.tsx
- src/pages/bookcase/BookCasePage.tsx
- src/pages/bookcase/components/ToolBoxButton.tsx
- src/pages/cd/components/CommentList.tsx
`style/housemate-modal` -> `dev`
- 알림 모달 및 하우스메이트 모달 퍼블리싱
- 알림 모달, 하우스메이트 모달, 숨김 메뉴에 애니메이션 효과 추가 (framer-motion 사용)
- list item에 cusor-pointer 주는 걸 깜빡했네요... 추가하겠습니다!
- 알림 종류에 따른 메시지를 변경은 API 연동하면서 해결할 예정입니다
- 메인 페이지의 다른 모달 및 메뉴는 애니메이션 효과가 있어서 결을 맞추려면 헤더의 메뉴들도 애니메이션 효과가 있어야 할 것 같아 추가했습니다!
pull 받으시면 보고 피드백 부탁드립니당
#73
> [style/housemate-modal] 💄Style: 하우스메이트 모달 및 알림 모달 퍼블리싱

- package.json
- pnpm-lock.yaml
- src/apis/cd.ts
- src/pages/cdrack/CdRackPage.tsx
- src/pages/cdrack/components/CdSwiper.tsx
- src/pages/cdrack/components/Dock.tsx
- src/pages/cdrack/components/NotEmptyStatus.tsx
- src/routes/Router.tsx
`feature/cdrack` -> `dev`
Dock 메뉴 페이지네이션 적용
> ✨ feat: dock 메뉴 페이지네이션 적용

- src/components/datalist/DataList.tsx
- src/components/datalist/EditStatusItem.tsx
- src/components/datalist/NoEditStatusItem.tsx
- src/mocks/mockCD.ts
- src/pages/cd/CdPage.tsx
- src/pages/cd/components/CdComment.tsx
- src/pages/cd/components/CdInfo.tsx
- src/pages/cd/components/CdPlayer.tsx
- src/pages/cd/components/CdTemplate.tsx
- src/pages/cd/components/EditTemplate.tsx
- src/pages/login/components/SocialTab.tsx
- src/routes/Router.tsx
- src/styles/scroll.css
- src/types/dataList.d.ts
`fix/cd` -> `dev`
cd 상세페이지 퍼블리싱 수정
- #84
> 🐛 fix: cd 상세페이지 퍼블리싱 수정

- src/apis/axiosInstance.ts
- src/apis/book.ts
- src/apis/profile.ts
- src/components/ConfirmModal.tsx
- src/components/profile-card/ProfileCardLayout.tsx
- src/components/search-modal/SearchResult.tsx
- src/hooks/useUserProfile.ts
- src/pages/profile-card-edit/ProfileCardEditPage.tsx
- src/pages/profile-card-edit/components/ProfileActions.tsx
- src/pages/profile-card-edit/components/ProfileForm.tsx
- src/pages/profile-card-edit/components/ProfileImageEdit.tsx
- src/pages/profile-card-edit/hooks/useProfileEdit.ts
- src/pages/profile-card/ProfileCardPage.tsx
- src/pages/profile-card/components/ProfileButtons.tsx
- src/pages/profile-card/components/RecommendedUsers.tsx
- src/pages/profile-card/hooks/useProfileData.ts
- src/routes/Router.tsx
- src/types/profile.d.ts
> [feature/profile-card] 이미지 수정 API 추가 및 회원 탈퇴 기능 구현

- src/components/datalist/DataList.tsx
`fix/datalist-cd` -> `dev`
컴포넌트 스크롤 오류 수정
cd 단일, 다중 삭제 구현
#121
> [fix/datalist-cd] 컴포넌트 스크롤 오류 수정 및 cd 단일, 다중 삭제 구현

- src/apis/cd.ts
- src/components/Pagination.tsx
- src/components/SkeletonItem.tsx
- src/pages/cd/components/CdComment.tsx
- src/pages/cd/components/CdPlayer.tsx
- src/pages/cd/components/CommentList.tsx
`feature/cd` -> `dev`
cd 상세페이지의 댓글 목록에서 삭제 기능을 구현하였습니다.
방주인이나 작성자만이 댓글을 삭제할 수 있습니다.
- #86
> ✨ feat: 댓글 삭제 기능 구현

- package-lock.json
- src/apis/room.ts
- src/components/Pagination.tsx
- src/pages/room/RoomPage.tsx
- src/pages/room/components/Guestbook.tsx
- src/pages/room/components/GuestbookMessage.tsx
- src/pages/room/components/GusetbookInput.tsx
- src/pages/room/components/RoomModel.tsx
- src/styles/main.css
- src/types/guestbook.d.ts
- src/types/room.d.ts
`feature/guestbook` -> `dev`
방명록 API 수정에 따른 로직 수정 및 예외처리
#108
> [Feat/guestbook] 방명록 API 수정 및 오류 수정

- src/apis/cd.ts
- src/components/search-modal/SearchModal.tsx
- src/components/search-modal/SearchResult.tsx
- src/pages/cdrack/CdRackPage.tsx
- src/pages/cdrack/components/CdSwiper.tsx
- src/pages/cdrack/components/Dock.tsx
- src/pages/cdrack/components/EmptyStatus.tsx
- src/pages/cdrack/components/NotEmptyStatus.tsx
- src/pages/cdrack/components/SlidingTitle.tsx
`fix/cdrack-2qa` -> `dev`
- #125
> [fix/cdrack] 🐛 fix: cd 렉 페이지 2차 QA -1

- src/apis/axiosInstance.ts
- src/apis/book.ts
- src/pages/book-editor/BookEditorPage.tsx
- src/pages/book-viewer/components/BookHeader.tsx
- src/pages/book-viewer/components/BookReviewDisplay.tsx
- src/pages/book-viewer/components/ReviewContent.tsx
- src/pages/book/BookPage.tsx
- src/pages/bookcase/BookCasePage.tsx
- src/routes/Router.tsx
`feat/book` -> `dev`
도서 목록 기본 조회 갯수 수정
서평 CRUD 엔드포인트 수정 (백엔드 명세 수정으로 인한 엔드포인트 수정)
에러 핸들링 (토스트 모달, 컨펌 모달 자체 컴포넌트로 수정)
도서 관련 라우팅 로직 수정
#132
> [feat/book] 서평 API 엔드포인트 수정 및 에러 핸들링 추가

- src/apis/cd.ts
- src/pages/cd/components/CdComment.tsx
- src/pages/cd/components/CdPlayer.tsx
- src/pages/cd/components/CommentList.tsx
- src/pages/cd/components/EditTemplate.tsx
- src/pages/cd/components/NotEditTemplate.tsx
`fix/cd` -> `dev`
cd api 바뀐 부분 수정
- #129
> 🐛 fix: api url 수정

- src/apis/cd.ts
- src/pages/cd/CdPage.tsx
- src/pages/cd/components/CdComment.tsx
- src/pages/cd/components/CdInfo.tsx
- src/pages/cd/components/CdPlayer.tsx
- src/pages/cd/components/CdTemplate.tsx
- src/pages/cdrack/CdRackPage.tsx
- src/pages/cdrack/components/Dock.tsx
- src/styles/range.css
`fix/cdrack-cd` -> `dev`
- cd rack 비어있는 상태일때 페이지 못불러오는 문제 수정
- cd 상세페이지 제목이 길 경우 cd 이미지가 밑으로 내려오는 문제 수정
- #143
> 🐛 fix: cd 랙 페이지 hot fix, cd 상세페이지 디자인 수정

- src/App.tsx
- src/apis/auth.ts
- src/apis/axiosInstance.ts
- src/constants/login.ts
- src/pages/login/components/SocialTab.tsx
- src/routes/Router.tsx
`fix/auth` -> `dev`
로그인 인증/인가 관련해서 코드 수정했습니다.
토큰 재발급 API를 응답 인터셉터에서만 불러오도록 수정했습니다.
- #145
> 145 fix/auth

- src/App.tsx
- src/apis/auth.ts
- src/apis/websocket.ts
- src/components/header/Header.tsx
- src/pages/main/MainPage.tsx
`feat/rank-system` -> `dev`
1. 웹소켓 연결 로직을 App.tsx -> Header.tsx로 이동
- 웹소켓 연결 시 토큰이 필요하므로 웹소켓 연결 로직을 앱 마운트 시점에서 로그인 후 리디렉트 시점으로 변경
- 메인 페이지가 구현 중이므로 충돌을 피해 헤더에 구현
2. WebSocketService 클래스 전면 리팩토링
- 메모리 누수 방지를 위한 이벤트 리스너 정리 로직 추가
- Map을 사용한 구독 관리 개선 (중복 구독 방지, 구독 일괄 해지 가능)
- 에러 처리 개선
- 중복 코드 제거
- 클린업 로직 추가
3. 디버그 로그 정리
> :rotating_light:Fix: 웹소켓 연결/ 해제 로직 수정

- src/apis/room.ts
- src/pages/main/components/HiveRooms.tsx
> 🚨Fix: 랭킹 집계 API 오류 수정

- src/apis/ranking.ts
- src/components/search-modal/SearchResult.tsx
- src/pages/room/RoomPage.tsx
`fix/book` -> `dev`
🚨Fix: 책장 업그레이드 로직 userId -> roomId 전달
✨Feature: 다른 유저의 방 방문시 방문 횟수 카운트하는 로직 추가
-> 룸페이지 방문시 현재 로그인 한 유저와 해당 방 주인의 아이디 비교 후 랭킹 카운트 로직 호출
#171
> [fix] 책장 업그레이드 로직 수정 및 다른 유저의 방 방문시 방문 횟수 카운트하는 로직 추가

- src/pages/book/BookPage.tsx
- src/pages/room/RoomPage.tsx
`fix/book` -> `dev`
도서 - 책 상세 조회 관련
다른 유저의 도서 상세 페이지 접근시 서평이 없는 경우 다시 목록으로 돌아가도록 구현했습니다
#171
> [fix/book] :sparkles:Feature: 다른 사용자의 도서 상세 조회시 서평이 없는 경우 리디렉트

- src/apis/point.ts
- src/constants/point.ts
- src/pages/login/components/SocialTab.tsx
- src/pages/point/PointPage.tsx
- src/pages/point/components/PointHistory.tsx
- src/styles/scroll.css
- src/types/point.d.ts
`feat/point` -> `dev`
포인트 내역 페이지(모달)  기능구현했습니다.
- #167
> ✨ feat: point 내역 페이지 기능 구현

- src/apis/cd.ts
- src/components/search-modal/SearchResult.tsx
- src/pages/cdrack/CdRackPage.tsx
- src/pages/cdrack/components/CdStatus.tsx
- src/pages/cdrack/components/Dock.tsx
`feat/cdrack-limit` -> `dev`
cd 렉페이지에서 cd 추가시 레벨 제한 해제 로직 구현
- #175
> ✨ feat: cd 레벨 해금 로직 연결

- src/pages/profile-card-edit/ProfileCardEditPage.tsx
- src/pages/profile-card/ProfileCardPage.tsx
- src/pages/profile-card/components/UserProfileSection.tsx
`feat/profile-card` -> `dev`
프로필 카드 이미 찌그러짐 해결 (object-cover)
포인트 조회 추가 -> toLocaleString('ko-KR')로 단위 구분 콤마 표시
프로필 수정시 에러 메시지 수정 (response의 에러 메시지로 수정)
#182
> [feat/profile-card] ✨Feature: 프로필 카드 포인트 조회 적용 / 풀백 UI 수정

- pnpm-lock.yaml
- src/apis/cd.ts
- src/components/search-modal/SearchResult.tsx
> [refactor/cd-search]✨ feat: cd 검색 관련 최적화 작업

- src/apis/housemate.ts
- src/components/header/menus/hooks/useHousemates.ts
- src/pages/profile-card/ProfileCardPage.tsx
- src/pages/profile-card/components/ProfileButtons.tsx
- src/pages/profile-card/hooks/useProfileData.ts
- src/types/profile.d.ts
`fix/housemate` -> `dev`
하우스메이트 API 호출시 cursor = housemateId로 수정
-> 하우스메이트 목록을 호출하는 컴포넌트의 id 값 수정
나의 프로필인지 여부를 판단하는 플래그 isMyProfile -> 프로필 조회시 받는 MyProfile 값으로 변경
팔로우 / 팔로잉 여부를 판단하는 플래그 isFollowing -> 프로필 조회시 받는 Following 값으로 변경
#189
> [fix/housemate] :rotating_light:Fix: 하우스메이트 목록 조회 API 수정 / 프로필 버튼 렌더링 조건 단순화

- src/pages/profile-card/ProfileCardPage.tsx
- src/pages/profile-card/components/RecommendedUsers.tsx
`fix/profile-card/point` -> `dev`
내 프로필카드에서만 포인트 버튼을 확인할 수 있도록 수정
#194
> [fix/profile-card/point] :lipstick:Style: 내 프로필카드에서만 포인트 버튼을 확인할 수 있도록 수정

- src/components/search-modal/SearchResult.tsx
- src/pages/cdrack/components/CdStatus.tsx
- src/pages/cdrack/components/CdSwiper.tsx
- src/pages/cdrack/components/Dock.tsx
- src/pages/cdrack/components/SlidingTitle.tsx
`style/cdrack` -> `dev`
cd 랙 페이지 디자인 최종 QA 
- 브랜치 삭제하지 말아주세요
- #199
> 💄 style: cd 랙 페이지 디자인 수정

- .github/workflows/workflow.yml
- src/pages/login/components/SocialTab.tsx
`hotfix/login` -> `dev`
- #199
> 🐛 hotfix: 소셜 로그인 배포 URL로 수정

- src/components/Pagination.tsx
- src/pages/main/hooks/useRooms.ts
> 🐛 fix: 메인페이지 undefined 오류 수정

- src/pages/login/LoginPage.tsx
- src/pages/login/components/AgreeTab.tsx
> 💄 style: 로그인 페이지 디자인 수정

- src/pages/event/EventPage.tsx
- src/pages/event/components/FailScreen.tsx
- src/pages/event/components/SuccessScreen.tsx
> 💄 style: 이벤트 페이지 디자인 수정

- src/pages/cdrack/CdRackPage.tsx
- src/pages/cdrack/components/CdStatus.tsx
- src/pages/cdrack/components/Dock.tsx
> 🐛 fix: cdrack 오류 수정3

- src/apis/book.ts
- src/components/Toast.tsx
- src/components/header/menus/housemate-modal/HousemateModal.tsx
- src/components/header/menus/modal/EmptyState.tsx
- src/components/header/menus/notification-modal/NotificationModal.tsx
- src/components/search-modal/SearchInput.tsx
- src/components/search-modal/SearchList.tsx
- src/components/search-modal/SearchModal.tsx
- src/hooks/useDebounce.tsx
- src/pages/bookcase/BookCasePage.tsx
- src/styles/scroll.css
`feature/` -> `dev`
알림/하우스메이트 모달 - 커스텀 스크롤로 변경
검색모달 - 스크롤 커스텀 스크롤로 변경
검색모달 - outline 색 변경
알림/하우스메이트 모달 - placeholder 가운데로 수정
토스트 - 위치를 헤더에 맞춰서 수정
도서 검색 API 백엔드 로직으로 수정
#225
> [fix/notification-qa] 모달 관련 최종 QA 해결 및 도서 검색 API 백엔드 로직으로 수정

- src/pages/cdrack/components/CdStatus.tsx
- src/pages/cdrack/components/CdSwiper.tsx
- src/pages/cdrack/components/Dock.tsx
`fix/cdrack` -> `dev`
cdrack 배포 오류 수정4
> 🐛 fix: cdrack 배포 오류 수정4

- src/pages/cdrack/components/CdStatus.tsx
- src/pages/cdrack/components/Dock.tsx
> 🐛 fix: cdrack 배포 오류 수정5

- src/pages/cd/components/CdComment.tsx
- src/pages/cd/components/CdInfo.tsx
- src/pages/event/EventPage.tsx
> 🐛 fix: cd 상세페이지 배포 오류 수정1

- src/pages/cdrack/components/CdStatus.tsx
`fix/cdrack` -> `dev`
- cdrack  배포상태에서 첫 cd 추가시 발생하는 에러 수정
> 🐛 fix: cdrack  배포상태에서 첫 cd 추가시 발생하는 에러 수정

- src/pages/event/EventPage.tsx
`hotfix/event` -> `dev`
이벤트 페이지에서 진행중인 이벤트가 없을때 버튼을 눌렀을경우 에러 예외처리가 되지않은 상황이라 그냥 disabled 처리시켰습니다.
> 🐛 fix : 진행중인 이벤트 없으면 disabled 처리

- src/pages/main/MainPage.tsx
- src/pages/main/components/HiveRooms.tsx
- src/pages/main/components/RankingModal.tsx
- src/pages/main/hooks/useHexagonGrid.ts
- src/pages/room/components/Guestbook.tsx
- src/pages/room/components/RoomModel.tsx
- src/types/render.d.ts
전반적인 메인의 배포 오류 수정
- (기존) directions 방향으로 확장 -> (변경) 왼쪽/오른쪽 방향으로 확장
- 기존 중복/구멍 배치 오류 수정
- 클릭시 방 이동에 관한 로직 분리로 UX 개선
- 사용자에게 익숙한 왼쪽 클릭으로 드래그 트리거 변경
- 포인트 조회 ( 타인도 볼 수 있도록 수정)
#231
> [Fix/main] 헥사곤 그리드 배치 및 드래그 수정

- src/pages/room/components/Guestbook.tsx
`fix/room` -> `dev`
방명록 배포시 오류 발생 수정
- guestbookData & pagination -> 옵셔널 체이닝 및 초기값 설정
#260
> 🚨Fix: 방명록 undefined 응답 처리

- src/pages/book-editor/BookEditorPage.tsx
- src/pages/book-viewer/components/ReviewContent.tsx
- src/pages/book/BookPage.tsx
- src/pages/bookcase/BookCasePage.tsx
- src/pages/bookcase/components/BookCaseList.tsx
`fix/book-write-edit` -> `dev`
서평 작성 완료시 뷰어 페이지로 리디렉트
서평이 없을 때 작성 페이지로 리디렉트하는 조건 수정
BookPage.tsx
```
// 404는 서평이 없는 경우로 처리
if (error.response?.status === 404)
```
수정 후
```
error?.response?.status === 200 ||
error?.response?.status === 201
```
성공 케이스를 200, 201일 때로 한정
#258
> [fix/book-write-edit] :rotating_light:Fix: 도서 작성시 페이지 라우팅 수정

- src/apis/point.ts
- src/pages/point/PointPage.tsx
- src/pages/point/components/PointHistory.tsx
- src/pages/profile-card/ProfileCardPage.tsx
- src/pages/room/components/RoomModel.tsx
`fix/room` -> `dev`
포인트 잔액 조회 API 수정
- API 로직 수정 -> userId 파라미터 추가
- 프로필 카드/룸/포인트 영수증 로직 수정(usserId 추가)
#263
> [Fix/room] 포인트 잔액 조회 수정

- src/apis/point.ts
- src/components/LayeredButton.tsx
- src/components/header/menus/HiddenMenu.tsx
- src/pages/bookcase/BookCasePage.tsx
- src/pages/bookcase/components/BookCaseList.tsx
- src/pages/point/PointPage.tsx
- src/pages/point/components/PointHistory.tsx
- src/pages/profile-card/ProfileCardPage.tsx
- src/pages/profile-card/components/RecommendedUserList.tsx
- src/pages/room/components/RoomModel.tsx
`fix//common-QA` -> `dev`
책장 페이지 / 아래쪽 패딩 주기
버튼 텍스트 드래그 막기
로그아웃 ↔ 로그아웃 아이콘 gap 1로 수정
프로필 카드 / 포인트 잔액 조회 API 수정 (토큰 → userId)
#266
> [fix/common-QA] 최종 QA 퍼블리싱 수정 및 프로필 카드 포인트 조회 API 수정

- src/pages/payment/PaymentPage.tsx
`style/payment` -> `dev`
포인트 충전 페이지 퍼블리싱 수정
#270
> [style/payment] :lipstick:Style: 포인트 충전 페이지 퍼블리싱 수정

- src/pages/cd/CdPage.tsx
- src/pages/cd/components/CdPlayer.tsx
- src/pages/cd/components/CommentList.tsx
- src/pages/cdrack/components/CdStatus.tsx
- src/pages/cdrack/components/CdSwiper.tsx
- src/pages/cdrack/components/Dock.tsx
- src/pages/event/EventPage.tsx
- src/pages/login/components/AgreeItem.tsx
`fix/deploy-khw` -> `dev`
-> 기본적으로 노래가 정지된 상태로 통일했습니다. 재생버튼을 누르면 노래가 재생되며 무한반복은 기본적으로 활성화되어 있게 했습니다.
- #256
> 🐛 fix: 배포환경에서 발생한 오류 수정

- src/components/Toast.tsx
`fix/toast` -> `dev`
:rotating_light:Fix: 토스트 테마 옵셔널 체이닝 추가
#278
> :rotating_light:Fix: 토스트 테마 옵셔널 체이닝 추가

- src/pages/main/MainPage.tsx
- src/pages/main/components/HiveRooms.tsx
무한 상태 변경 오류 수정
무한 상태 변경 오류 수정
#281
> 🚨Fix: 무한 상태 변경 로직 수정

- src/components/datalist/DataList.tsx
- src/pages/cd/components/CdTemplate.tsx
- src/pages/cd/components/EditTemplate.tsx
- src/pages/cd/components/NotEditTemplate.tsx
- src/pages/cdrack/components/CdStatus.tsx
> 🐛 fix: 첫 cd 추가시 오류 수정

- src/pages/cdrack/components/CdStatus.tsx
- src/pages/cdrack/components/CdSwiper.tsx
- src/pages/cdrack/components/Dock.tsx
`fix/cd` -> `dev`
CD Rack 퍼블리싱 수정
#288
> 💄 style: cd 퍼블리싱 수정

- src/pages/book-viewer/components/ReviewContent.tsx
`fix/final-book-QA` -> `dev`
#295
> [fix/final-book-QA] 

- src/pages/cdrack/components/CdStatus.tsx
- src/pages/cdrack/components/Dock.tsx
`fix/cdrack-dock` -> `dev`
- #256
> 🐛 fix: cd 추가,삭제시 이전,다음버튼 활성화 오류 수정

- src/pages/room/components/Guestbook.tsx
- src/pages/room/components/GuestbookMessage.tsx
- src/pages/room/components/GusetbookInput.tsx
- src/pages/room/components/RoomModel.tsx
`fix/room` -> `dev`
방 조명 세팅 및 방명록 레이아웃 수정
방 조명 세팅 및 방명록 레이아웃 수정
#310
> 💄 style: 방 조명 및 방명록 레이아웃 수정

- src/components/datalist/DataList.tsx
- src/components/datalist/EditStatusItem.tsx
- src/components/header/menus/hooks/useHousemates.ts
- src/components/header/menus/housemate-modal/HousemateModal.tsx
- src/components/header/menus/notification-modal/NotificationModal.tsx
- src/pages/book-editor/BookEditorPage.tsx
- src/pages/book-viewer/BookViewerPage.tsx
- src/pages/bookcase/BookCasePage.tsx
- src/pages/bookcase/components/BookCaseList.tsx
- src/pages/bookcase/components/ToolBoxButton.tsx
- src/pages/profile-card/components/GenreCard.tsx
- src/pages/profile-card/components/RecommendedUserList.tsx
- src/pages/profile-card/components/RecommendedUserListItem.tsx
`fix/final-book-QA` -> `dev`
배포 QA
> [fix/final-book-QA] 최종 배포 QA

- src/pages/room/components/PreferenceSettingCard.tsx
`fix/room` -> `dev`
취향 카드 간격 수정
취향 카드 간격 수정
> 💄Style: 카드 간격 수정

- src/components/header/menus/modal/BaseModal.tsx
- src/components/header/menus/notification-modal/components/NotificationItem.tsx
- src/components/header/menus/notification-modal/components/NotificationMessage.tsx
- src/pages/book-editor/BookEditorPage.tsx
- src/pages/book-editor/components/ReviewTextField.tsx
- src/pages/book-viewer/BookViewerPage.tsx
- src/pages/book-viewer/components/ReviewContent.tsx
- src/types/notification.d.ts
`fix/book-style` -> `dev`
에디터 작성시 제목 및 필드 1개 필수값 처리
서평 작성시 개행 처리
서평 뷰어 페이지에서 도서 이미지 크기 반응형
알림 타입 추가(포인트)
알림 / 하우스메이트 모달 패딩값 줄이기
관리자 알림 -> 기본 프로필 추가
#318
> [fix/book-style] 서평 작성시 개행 처리 / 알림 타입 추가

- src/pages/room/components/GusetbookInput.tsx
`feature/guestbook` -> `dev`
방명록 글자 수 표기
방명록 글자 수 표기
> ✨Feature: 방명록 글자 수 표기

- src/pages/room/components/GusetbookInput.tsx
`fix/guestbook` -> `dev`
방명록 표기 해상도 고려 수정
방명록 표기 해상도 고려 수정
> 🚨 Fix: 해상도 고려 수정

- src/apis/cd.ts
- src/pages/book-viewer/components/BookInfo.tsx
- src/pages/cd/components/CdComment.tsx
- src/pages/cd/components/CdPlayer.tsx
- src/pages/cd/components/CommentList.tsx
- src/pages/cdrack/components/CdSwiper.tsx
- src/pages/cdrack/components/Dock.tsx
- src/pages/event/EventPage.tsx
- src/pages/main/components/TopRankingItem.tsx
- src/pages/point/components/PointHistory.tsx
> [fix/deploy] 배포환경에서 발생한 오류 최종 수정

- src/pages/book-editor/BookEditorPage.tsx
- src/pages/book-editor/components/FreeformEditor.tsx
- src/pages/book-viewer/BookViewerPage.tsx
- src/pages/book-viewer/components/BookInfo.tsx
- src/pages/book-viewer/components/BookReviewDisplay.tsx
- src/pages/book/BookPage.tsx
- src/pages/bookcase/BookCasePage.tsx
`fix/book` -> `dev`
도서 뷰어 페이지 북커버 사이즈 줄이기
제목/내용을 작성하지 않고 저장하기를 눌렀을 때 토스트 메시지 피드백 추가
풀백 UI 언어 톤 통일 (습니다. -> 했어요! 로 전체적으로 가볍고 발랄한 톤으로 통일)
자유 형식 글쓰기 수정시 에디터에 표시가 되지 않는 문제 해결
#331
> [fix/book] 도서 관련 배포 QA 해결 (풀백 UI / 서평 수정시 에디터 문제 등)

- package-lock.json
- src/pages/main/hooks/useHexagonGrid.ts
3번째 링부터 아래쪽에만 배치되는 문제 해결
모든 위치를 순회하게 수정하며, 조건 강화
> 🚨Fix: 3번째 링부터 아래쪽만 배치되는 문제해결

- src/apis/auth.ts
- src/apis/axiosInstance.ts
- src/constants/login.ts
- src/hooks/event/useFetchEvent.ts
- src/pages/event/EventPage.tsx
- src/pages/event/components/ResultScreen.tsx
- src/pages/login/components/Redirection.tsx
- src/routes/Router.tsx
- src/types/event.d.ts
> [refactor/event] 이벤트 페이지 리팩토링 (커스텀 훅 분리, 컴포넌트 분리)

- index.html
- src/hooks/cdrack/useFetchCdLists.ts
- src/pages/cdrack/CdRackPage.tsx
- src/pages/cdrack/components/CdStatus.tsx
- src/pages/cdrack/components/CdSwiper.tsx
- src/pages/point/PointPage.tsx
> 🔨 refactor: cd rack 페이지 성능 개선

- index.html
- src/pages/cdrack/components/CdStatus.tsx
- src/pages/cdrack/components/CdSwiper.tsx
> 🔨 refactor: cd rack 페이지 성능 개선 2차

- src/pages/cdrack/components/CdStatus.tsx
- src/pages/cdrack/components/CdSwiper.tsx
> 🔨 refactor: cd rack 페이지 성능 개선 3차

- src/pages/cd/components/CdInfo.tsx
> 🔨 refactor: 빈 CD이미지 preload

- src/components/datalist/DataList.tsx
- src/hooks/cd/useCdPlayerState.ts
- src/hooks/cd/useFetchSearchCdLists.ts
- src/hooks/cd/useYoutubeControls.ts
- src/hooks/cd/useYoutubeEvent.ts
- src/pages/cd/components/comments/CdComment.tsx
- src/pages/cd/components/comments/CdCommentForm.tsx
- src/pages/cd/components/comments/CommentListButton.tsx
- src/pages/cd/components/comments/VisibleCommentList.tsx
- src/pages/cd/components/player/CdPlayer.tsx
- src/pages/cd/components/player/LeftGroup.tsx
- src/pages/cd/components/player/MiddleGroup.tsx
- src/pages/cd/components/player/RightGroup.tsx
- src/types/cd.d.ts
- src/types/dataList.d.ts
> 🔨 refactor: cd player 컴포넌트 리렌더링 최소화

- src/apis/cd.ts
- src/hooks/cd/useFetchCdComments.ts
- src/hooks/cd/useMutateCdComments.ts
- src/pages/cd/components/comments/CdCommentForm.tsx
- src/pages/cd/components/comments/CommentListModal.tsx
`fix/cd` -> `dev`
- cd 댓글 2번찍히는 문제 수정
- 첫렌더링시 모든 댓글들이 바로 보이는 문제 수정
> 🚨 fix: cd 댓글 오류 수정
